export let GET_USER_PANDING = "GET_USER_PANDING";
export let GET_USER_SUCCESS = "GET_USER_SUCCESS";
export let GET_USER_ERROR = "GET_USER_ERROR";

export let POST_USER_PANDING = "POST_USER_PANDING";
export let POST_USER_SUCCESS = "POST_USER_SUCCESS";
export let POST_USER_ERROR = "POST_USER_ERROR";

export let DELETE_USER_PANDING = "DELETE_USER_PANDING";
export let DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export let DELETE_USER_ERROR = "DELETE_USER_ERROR";

export let UPDATE_USER_PANDING = "UPDATE_USER_PANDING";
export let UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export let UPDATE_USER_ERROR = "UPDATE_USER_ERROR";


